version: '3.8'
services:
  livekit-server:
    container_name: livekit-server
    image: livekit/livekit-server:latest
    ports:
      - "7880:7880"
    volumes:
      - ./config.yaml:/config.yaml
    command: --config /config.yaml
    environment:
      - CONFIG_FILE=/config.yaml
      - LIVEKIT_API_KEY=108cc770f923cf669912dfed679c73c3
      - LIVEKIT_API_SECRET=2c0c06d6975ee23e9ae32460ff0599b4

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"    # HTTP port
      - "443:443"  # HTTPS port, if configured
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Custom Nginx configuration
    depends_on:
      - livekit-server

networks:
  default:
    name: livekit_network